version: '{build}'
os: Windows Server 2012
install:
  - cmd: SET JAVA_HOME=C:\Program Files (x86)\Java\jdk1.8.0
  - cmd: SET LIBSODIUM_VERSION=1.0.3
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\libsodium" )) {
        (New-Object System.Net.WebClient).DownloadFile(
          "https://github.com/jedisct1/libsodium/archive/$env:LIBSODIUM_VERSION.zip",
          'C:\libsodium.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\libsodium.zip", "C:\")
        Rename-Item C:\libsodium-$env:LIBSODIUM_VERSION C:\libsodium
      }
  - cmd: msbuild C:\libsodium\libsodium.vcxproj /property:Configuration=ReleaseDLL /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cmd: SET PATH=C:\libsodium\Build\ReleaseDLL\Win32;%PATH%
build_script:
  - mvn clean install -q --batch-mode -DargLine=-Dfile.encoding=windows-1251
cache:
  - C:\libsodium
  - C:\Users\appveyor\.m2
